[workspace]
authors = ["Justus Magin <keewis@posteo.de>"]
channels = ["conda-forge"]
name = "emscripten-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
maturin = ">=1.12.6,<2"
python = "3.13.*"

[pypi-dependencies]
pyemscripten = { path = ".", editable = true }

[feature.rattler.dependencies]
rattler-build = "*"

[feature.rattler.tasks.build-emscripten]
cmd = [
  "rattler-build",
  "build",
  "--package-format",
  "tar-bz2",
  "-c",
  "https://repo.prefix.dev/emscripten-forge-4x",
  "-c",
  "conda-forge",
  "--output-dir",
  "target/conda",
  "--recipe",
  "recipe.yml",
  "--target-platform",
  "emscripten-wasm32",
]
cwd = "."

[feature.docs.dependencies]
sphinx = "*"
jupyterlite-sphinx = "*"
jupyterlite-xeus = ">=4.4.2,<5"

[feature.docs.tasks]
build-docs = { cmd = "make html", cwd = "docs" }
host-docs = { cmd = "python -m http.server -b 127.0.0.1 -d _build/html 5447", default-environment = "docs", cwd = "docs" }

[environments]
rattler = ["rattler"]
docs = ["docs"]
