context:
  name: pyemscripten
  version: 0.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - path: .

build:
  number: 0

  script:
    - export MATURIN_PYTHON_SYSCONFIGDATA_DIR=${PREFIX}/etc/conda/_sysconfigdata__emscripten_wasm32-emscripten.py
    - ${PYTHON} -m pip install . -vvv

  python:
    skip_pyc_compilation:
      - "**/*.py"

requirements:
  build:
    - maturin
    - cross-python_${{ target_platform }}
    - rust-nightly
  host:
    - python
    - setuptools-rust
  run:
    - python

tests:
  - script:
      - echo "FIXME:"
  # - python:
  #     imports:
  #       - pyemscripten

about:
  summary: emscripten test
  license: Apache-2.0
  license_file: LICENSE
